name: jobpulse
description: A job finder application

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+2

environment:
  sdk: '>=3.1.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.7.0
  cloud_firestore: ^4.4.3
  firebase_auth: ^4.2.9
  firebase_storage: ^11.0.14
  flutter_svg: ^2.0.2
  image_picker: ^0.8.6+4
  provider: ^6.0.5
  flutter_native_splash: ^2.3.0
  uuid: ^3.0.7
  pull_to_refresh: ^2.0.0
  cupertino_icons: ^1.0.2
  get_it: ^7.6.0
  camera: ^0.10.5+2
  google_fonts: ^4.0.5
  shared_preferences: ^2.1.1
  fluttertoast: ^8.2.2
  timeago: ^3.5.0
  intl: ^0.18.1
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/ic_launcher.png"